"""The submission artifacts, and the two ways they can quietly go wrong.

Both failures this file guards against were real. A figure was generated by
``src/figures.py``, committed, archived on Zenodo, and cited by nothing --
found by eye while wiring up the export, not by anything failing. And an
anonymised build is the kind of artifact whose defect is invisible in the
thing itself: a PDF with the author's name still in it looks exactly like one
without, until a reviewer opens it.

A third failure was not: "2023's" rendered as "2023-prime-s" in the PDF while
the markdown held an ordinary apostrophe, because the build turned it into one
character and typst turned that into another. See the Typography section.

The document-shaping logic is pure Python and is tested directly, so the suite
runs without pandoc; the two tests that drive a real build skip when the tools
they need are absent.
"""
import functools
import json
import re
import shutil
import unicodedata

import pytest

from src import export, report

ROOT = export.ROOT
FIG_DIR = ROOT / "figures"


@pytest.fixture(scope="module")
def identity():
    return export.Identity.load()


@pytest.fixture(scope="module")
def built():
    return export.SOURCE.read_text(encoding="utf-8")


# --------------------------------------------------------------------------
# Figures
# --------------------------------------------------------------------------


def test_every_generated_figure_is_cited(built):
    """A figure nobody cites is a figure nobody meant to publish.

    fig2_age_specific_rates.png was generated, committed and archived while
    the manuscript referred to figures 1, 5, 3 and 4 and never to it. The
    export embeds what the manuscript cites, so an uncited figure silently
    does not ship -- and an archive that carries an image the paper never
    mentions invites the reader to wonder what it was for.
    """
    on_disk = {p.name for p in FIG_DIR.glob("*.png")}
    cited = set(re.findall(r"\((?:figures/)([\w.-]+\.png)\)", built))
    assert on_disk, "no figures found; run python -m src.report"
    assert on_disk == cited, (
        f"generated but never cited: {sorted(on_disk - cited)}; "
        f"cited but not generated: {sorted(cited - on_disk)}"
    )


def test_figures_use_image_syntax_not_filename_prose(built):
    """Captions must be markdown images, or the export ships filenames.

    The manuscript used to carry lines like "*Figure 1:
    `figures/fig1_crude_vs_adjusted.png`*", which is prose naming a file. It
    renders as literal text in Word and in a PDF, so a reviewer receives the
    path instead of the plot.
    """
    offenders = [
        ln for ln in built.splitlines()
        if "figures/" in ln and not ln.lstrip().startswith("![")
    ]
    assert not offenders, (
        "figure referenced as text rather than an embedded image:\n  "
        + "\n  ".join(offenders)
    )


def test_every_table_has_a_caption(built):
    """Both tables carry a `Table:` caption pandoc can turn into a real one."""
    tables = built.count("\n|---")
    captions = len(re.findall(r"^Table: ", built, re.M))
    assert tables == captions == 2, (
        f"{tables} tables but {captions} captions; a table without a caption "
        "arrives in Word as an unlabelled grid"
    )


# --------------------------------------------------------------------------
# Document shaping
# --------------------------------------------------------------------------


def test_internal_notes_do_not_reach_a_submission(identity):
    md = export.prepare(identity, anonymous=False)
    for marker in export.INTERNAL_MARKERS:
        assert marker not in md, f"internal note reached the submission: {marker!r}"


def test_identity_comes_from_the_citation_record(identity):
    """Retyping the author into the exporter is the drift this avoids."""
    md = export.prepare(identity, anonymous=False)
    assert identity.author == "Terry Finberg"
    assert identity.orcid.endswith("0009-0006-1598-4200")
    assert identity.author in md
    assert export.AFFILIATION in md
    assert identity.orcid in md
    assert identity.title.startswith("Decomposing U.S. Crude Death Rates")


def test_keywords_survive_and_respect_the_ten_limit(identity):
    """Demographic Research allows up to ten; CITATION.cff is the source."""
    assert 1 <= len(identity.keywords) <= 10
    md = export.prepare(identity, anonymous=False)
    for kw in identity.keywords:
        assert kw in md


def test_keywords_are_visible_prose_not_a_metadata_key(identity):
    """The keywords line is in the body, and the YAML key must stay gone.

    Two things depend on this. Pandoc 3.6.2's typst template renders a
    keywords list as `keywords: (,,,,,,,,,)` -- separators without values --
    and typst then refuses to compile, so the PDF silently stopped being a
    PDF and fell back to a browser. And Demographic Research wants the
    keywords *listed in the file*, which a document property nobody opens
    does not satisfy.
    """
    md = export.prepare(identity, anonymous=False)
    front = md.split("---", 2)[1]
    assert "keywords:" not in front, (
        "keywords are back in the YAML block; this breaks the typst PDF"
    )
    assert "**Keywords:** " + ", ".join(identity.keywords) in md


CONCEPT_DOI = "10.5281/zenodo.22263667"


def test_nothing_in_the_archive_names_its_own_version_doi(built, identity):
    """A deposit cannot contain the identifier of the deposit containing it.

    Zenodo mints a version DOI when it archives the release, which is after
    the commit the release is cut from. So a version DOI written into the
    manuscript or into CITATION.cff's `doi:` is either an identifier that
    does not exist yet or the *previous* release's, attached to a new version
    number -- which is what this file read before v0.1.1, and is the same
    class of error as a date-released describing a release that never
    happened.

    Version DOIs belong on the Zenodo record and under CITATION.cff's
    `identifiers:`, added after their release was archived.
    """
    assert identity.version_doi == CONCEPT_DOI, (
        f"CITATION.cff `doi:` is {identity.version_doi!r}; it must be the "
        f"concept DOI {CONCEPT_DOI!r}. Version DOIs go under identifiers:."
    )
    found = set(re.findall(r"10\.5281/zenodo\.\d+", built))
    assert found == {CONCEPT_DOI}, (
        f"the manuscript cites {sorted(found)}; it may cite only the concept "
        f"DOI. A version DOI in the manuscript cannot be true at tag time."
    )


def test_the_manuscript_names_the_release_from_the_citation_record(built):
    """`v{{RELEASE_VERSION}}` must agree with CITATION.cff, not be typed."""
    version = report._release_version()
    assert f"release `v{version}`" in built
    template = (ROOT / "paper" / "manuscript.md").read_text(encoding="utf-8")
    assert "{{RELEASE_VERSION}}" in template, (
        "the release string was typed into the template; it goes stale at the "
        "next tag"
    )


def test_the_browser_fallback_is_opt_in(monkeypatch, tmp_path):
    """A missing engine must fail, not quietly produce a browser PDF.

    It used to fall back silently-in-effect: the run printed one line naming
    the engine, and one line is easy to miss. The resulting PDF is
    indistinguishable from a good one without reading its metadata, which is
    a bad way to find out after a preprint is posted.
    """
    monkeypatch.setattr(export, "find_pdf_engine", lambda: None)
    with pytest.raises(export.ExportError, match="opt-in"):
        export.build_pdf("# x\n", tmp_path / "out.pdf", allow_browser=False)


def test_the_fallback_reports_itself_as_a_fallback():
    """Whatever the browser path returns must be recognisable as one.

    run() decides whether to print the warning by looking for "fallback" in
    the engine string, so that word carries load and a rename would silence
    the warning without failing anything.
    """
    src = (ROOT / "src" / "export.py").read_text(encoding="utf-8")
    assert 'headless (fallback)"' in src
    assert '"fallback" in engine' in src


def test_the_typst_path_names_a_font(identity):
    """typst 0.15 rejects an empty font fallback list, which is pandoc's default.

    Without an explicit font the document does not compile at all. The face
    named must be one typst bundles, or the build stops being reproducible
    across machines.
    """
    assert export.TYPST_FONT
    assert export.TYPST_FONT in ("Libertinus Serif", "New Computer Modern")


# --------------------------------------------------------------------------
# Typography
# --------------------------------------------------------------------------

# Every non-ASCII character the manuscript is allowed to contain, named. An
# allowlist and not a blocklist: the character that got through was one nobody
# had thought to look for, and a blocklist only ever contains characters
# somebody already thought of.
#
# The em dash is absent deliberately and is not an oversight. It is house
# style, not a typo, so nothing else would have caught it coming back.
ALLOWED_NON_ASCII = {
    "‘": "left single quotation mark",
    "’": "right single quotation mark",
    "“": "left double quotation mark",
    "”": "right double quotation mark",
    "–": "en dash",
}

# `README.md` and `STATUS.md` are working documents rather than submitted
# ones, and they carry marks the paper never should: section signs, arrows, a
# status tick, the middle dot in their header rules, and the prime in the
# treatment names A/B/C'.
#
# They also have to be able to *show* the character the manuscript must not
# contain. Three of the four primes in them are the "2023's" defect being
# quoted, and a document explaining a typographic fault cannot do it without
# displaying the fault. So the prime is allowed here and refused two lines
# above, which is the distinction this pair of lists exists to draw.
#
# The em dash is absent from both. That is the whole point of adding these two
# files: the sweep that removed 88 of them was a one-off, and nothing stopped
# the next one arriving.
ALLOWED_IN_NOTES = ALLOWED_NON_ASCII | {
    "§": "section sign",
    "·": "middle dot",
    "…": "horizontal ellipsis",
    "′": "prime",
    "←": "leftwards arrow",
    "→": "rightwards arrow",
    "✅": "white heavy check mark",
}

# Everything the reader receives, not only the paper. `.zenodo.json` supplies
# the archive's title, description and keywords, and an em dash reached the
# published record through it while the manuscript sweep passed clean.
TYPOGRAPHY_SOURCES = {
    "paper/manuscript.md": ALLOWED_NON_ASCII,
    "paper/manuscript_built.md": ALLOWED_NON_ASCII,
    ".zenodo.json": ALLOWED_NON_ASCII,
    "README.md": ALLOWED_IN_NOTES,
    "STATUS.md": ALLOWED_IN_NOTES,
}

# Passages exempted by hand: (file, exact text, why). Deliberately a passage
# and not a character or a file, so an exemption licenses the one place it was
# written for and nothing else.
TYPOGRAPHY_EXEMPTIONS = (
    (
        "STATUS.md",
        '"has no callers in the repo — this is fresh API surface being '
        'introduced by this PR."',
        "verbatim quotation of an external review; repunctuating it misquotes it",
    ),
)


def _typography_chunks(
    relative: str,
    exemptions: tuple[tuple[str, str, str], ...] = TYPOGRAPHY_EXEMPTIONS,
) -> list[tuple[str, str]]:
    """(where, text) pairs to inspect, one per line or per JSON string.

    JSON is decoded rather than scanned as text, because `\\u2014` and a
    literal em dash are the same character to a reader and different bytes to
    a grep. Scanning the raw file would pass the escaped form, which is the
    form an editor is most likely to write.

    Exempted passages are removed here rather than skipped in the caller, so
    an exemption cannot accidentally widen to the rest of its line.
    """
    path = ROOT / relative
    raw = path.read_text(encoding="utf-8")
    if path.suffix != ".json":
        chunks = [(f"line {n}", line)
                  for n, line in enumerate(raw.splitlines(), start=1)]
    else:
        chunks = []

        def walk(node, where: str) -> None:
            if isinstance(node, str):
                chunks.append((where, node))
            elif isinstance(node, dict):
                for key, value in node.items():
                    walk(key, where)
                    walk(value, f"{where}.{key}" if where else key)
            elif isinstance(node, list):
                for i, value in enumerate(node):
                    walk(value, f"{where}[{i}]")

        walk(json.loads(raw), "")

    excused = [text for source, text, _ in exemptions if source == relative]
    for text in excused:
        found = sum(chunk.count(text) for _, chunk in chunks)
        if found != 1:
            raise AssertionError(
                f"stale typography exemption for {relative}: expected exactly "
                f"one occurrence of {text[:60]!r}, found {found}. An exemption "
                "covering nothing is worse than no exemption -- it looks "
                "identical to a working one, and the next passage that happens "
                "to match inherits a licence nobody granted. Remove it, or "
                "restore the passage it was written for."
            )
    if excused:
        chunks = [
            (where, functools.reduce(lambda s, t: s.replace(t, " "), excused, chunk))
            for where, chunk in chunks
        ]
    return chunks


@pytest.mark.parametrize("relative", sorted(TYPOGRAPHY_SOURCES))
def test_documents_use_only_allowed_characters(relative):
    """A character nobody chose must not reach a published record.

    Both of us read the abstract page and neither saw that "2023's" had
    rendered as "2023-prime-s". That is the shape of the problem: it is not
    illegible, it is almost right, so proofreading slides over it. The same
    thing then happened again in the Zenodo description, which no sweep of
    the manuscript could have covered.

    The manuscript's allowlist is deliberately short. Adding to it should mean
    deciding that a character belongs in the paper, which is a different act
    from letting one arrive.
    """
    allowed = TYPOGRAPHY_SOURCES[relative]
    offenders: dict[str, list[str]] = {}
    for where, text in _typography_chunks(relative):
        for char in text:
            if ord(char) > 126 and char not in allowed:
                offenders.setdefault(char, []).append(where)
    assert not offenders, "\n".join(
        f"U+{ord(c):04X} {unicodedata.name(c, 'unnamed')} in {relative} at "
        + ", ".join(dict.fromkeys(ws))
        for c, ws in sorted(offenders.items())
    )


def test_a_stale_typography_exemption_is_an_error():
    """An exemption that covers nothing must fail, not sit there quietly.

    The same reasoning as the anonymisation leak check two sections down. A
    rule that has stopped matching is indistinguishable from one that is
    working, and this one is a standing licence to write an em dash.
    """
    with pytest.raises(AssertionError, match="stale typography exemption"):
        _typography_chunks(
            "STATUS.md",
            (("STATUS.md", "a passage no longer in the file", "gone"),),
        )


def test_the_typst_path_disables_the_writers_smart_extension():
    """The prime came from the PDF build, not from the manuscript.

    This is the test that would have caught it, and the allowlist above is
    not: paper/manuscript.md held a plain ASCII apostrophe the whole time.
    Pandoc's typst writer normalises U+2019 back to `'` and lets typst
    re-smarten it, and typst turns an apostrophe after a digit into a prime
    because 5'11" is the case that rule exists for. Editing the source could
    not have fixed it; the writer discarded the character either way.

    `--to typst-smart` turns the writer's smart extension off, so it emits
    real punctuation and pandoc's template tells typst to leave it alone.
    """
    src = (ROOT / "src" / "export.py").read_text(encoding="utf-8")
    typst_branch = src.split('elif writer == "typst":', 1)[1].split("_pandoc(", 1)[0]
    assert '"typst-smart"' in typst_branch, (
        "the typst build no longer passes --to typst-smart; an apostrophe "
        "after a digit will render as a prime again"
    )


@pytest.mark.skipif(shutil.which("pandoc") is None, reason="pandoc not installed")
def test_the_typst_source_carries_real_punctuation(tmp_path):
    """The flag above is intent; this is the mechanism, checked on real output.

    Two things have to hold together and either alone is insufficient. The
    writer must emit U+2019 rather than an ASCII apostrophe, and the document
    must tell typst not to re-smarten what it is given. Assert both on the
    typst source pandoc actually generates, which needs no typst and no PDF
    reader, so it runs rather than skipping.
    """
    out = tmp_path / "probe.typ"
    export._pandoc(
        "The restatement moved 2023's population, and NVSR's rate.\n",
        out, "typst", ["--to", "typst-smart"],
    )
    source = out.read_text(encoding="utf-8")
    assert "2023’s" in source, (
        "the typst writer emitted an ASCII apostrophe; typst will render it "
        "as a prime after a digit"
    )
    assert "#set smartquote(enabled: false)" in source, (
        "typst was left free to re-smarten the punctuation pandoc chose"
    )


# --------------------------------------------------------------------------
# The ASCII abstract
# --------------------------------------------------------------------------


def test_the_ascii_abstract_is_ascii(tmp_path):
    """The whole point of the artifact, asserted directly."""
    out = export.build_abstract(tmp_path / "abstract.txt")
    body = out.read_text(encoding="ascii")
    assert body.strip()
    assert body.isascii()


def test_the_ascii_abstract_keeps_the_abstract_and_stops_there(tmp_path):
    """It must be the abstract, not the front matter and not section 1."""
    body = export.build_abstract(tmp_path / "abstract.txt").read_text()
    assert "crude death rate" in body
    assert "## " not in body
    assert "Introduction" not in body
    assert "**" not in body and "`" not in body


def test_an_unmapped_character_is_an_error_not_a_silent_deletion():
    """encode("ascii", "ignore") is the wrong tool and this says why.

    A dropped character leaves a sentence that still reads plausibly, which
    is how it survives review. The build stops instead, naming the character.
    """
    with pytest.raises(export.ExportError, match="U\\+2603"):
        export.to_ascii("a snowman ☃ walks in")


def test_every_allowed_manuscript_character_has_an_ascii_mapping():
    """Whatever typography the manuscript permits, the abstract can carry.

    These two tables are the same policy seen from both ends. A character
    added to the allowlist and not to the mapping would pass every test here
    and fail on the submission form.
    """
    missing = sorted(set(ALLOWED_NON_ASCII) - set(export.ASCII_PUNCTUATION))
    assert not missing, (
        "allowed in the manuscript but unmapped in ASCII_PUNCTUATION: "
        + ", ".join(f"U+{ord(c):04X}" for c in missing)
    )


# --------------------------------------------------------------------------
# Anonymisation
# --------------------------------------------------------------------------


def test_anonymous_build_carries_nothing_identifying(identity):
    md = export.prepare(identity, anonymous=True)
    # prepare() runs the assertion itself; run it again explicitly so this
    # test fails here rather than somewhere inside the builder.
    export._assert_anonymous(md)
    for pattern in export.IDENTIFYING:
        assert not re.search(pattern, md, re.I), f"leaked: {pattern}"


def test_anonymous_build_still_declares_availability(identity):
    """Stripped, not deleted.

    A reviewer must be able to see that the statement exists and was withheld.
    A submission with no data availability statement reads as an author who
    did not write one.
    """
    md = export.prepare(identity, anonymous=True)
    assert "**Data availability.**" in md
    assert "withheld from this anonymised copy" in md
    assert "**Author contributions.**" in md
    assert "**ORCID.**" not in md


def test_the_leak_check_actually_catches_a_leak():
    """A checker with a hole in it reports the absence of a search as a pass."""
    with pytest.raises(export.ExportError, match="identifying"):
        export._assert_anonymous("Written by Terry Finberg.")
    with pytest.raises(export.ExportError, match="identifying"):
        export._assert_anonymous("See https://github.com/someone/repo")


def test_anonymous_and_identified_differ_only_where_intended(identity):
    """The science must be byte-identical; only the front matter moves."""
    ident = export.prepare(identity, anonymous=False)
    anon = export.prepare(identity, anonymous=True)
    marker = "## 1. Introduction"
    assert ident[ident.index(marker):ident.index("## Declarations")] == \
        anon[anon.index(marker):anon.index("## Declarations")]


# --------------------------------------------------------------------------
# Engine reporting
# --------------------------------------------------------------------------


@pytest.mark.skipif(shutil.which("pandoc") is None, reason="pandoc not installed")
def test_pandoc_accepts_the_prepared_document(identity, tmp_path):
    """The metadata block and filter must survive a real pandoc run."""
    md = export.prepare(identity, anonymous=False)
    out = tmp_path / "smoke.docx"
    export.build_docx(md, out)
    assert out.exists() and out.stat().st_size > 0


def test_new_band_tokens_are_derived_not_typed():
    """Section 4.1 and 5.1 quote band figures; all of them must be tokens."""
    res = json.loads((ROOT / "data" / "processed" / "results.json").read_text())
    flat = report._flatten(res)
    for token in (
        "AGE_BANDS_TOTAL_WORD", "AGE_BANDS_FALLING_WORD",
        "AGE_BANDS_RISING_WORD", "AGE_BANDS_RISING_LIST",
        "AGE_BAND_RISE_MAX_GROUP", "AGE_BAND_RISE_MAX_PCT",
        "AGE_BAND_RISE_MAX_PCT_PRE", "AGE_BANDS_RISING_DEATH_SHARE",
    ):
        assert token in flat, f"{token} is quoted by the manuscript but not derived"
    # The band named as the worst reversal must actually be the worst one.
    rising = [b for b in res["age_band_change"] if b["pct_change"] > 0]
    worst = max(rising, key=lambda b: b["pct_change"])
    assert flat["AGE_BAND_RISE_MAX_GROUP"] == worst["age_group"]
