"""Build submission artifacts from the generated manuscript.

The same principle as ``report.py``, one level out. ``report.py`` exists so a
number cannot reach the paper without the code having produced it; this module
exists so a *submission* cannot reach a journal without the manuscript having
produced it. Nothing here is hand-assembled: the input is
``paper/manuscript_built.md``, which is itself generated, and the author
identity comes out of ``CITATION.cff`` rather than being retyped. A title page
that disagrees with the citation record is the same two-places-disagree failure
the repository already guards against elsewhere.

Two targets, two venues:

    python -m src.export --pdf     medRxiv
    python -m src.export --docx    Demographic Research, which prefers Word
    python -m src.export           both

Anonymised variants, for a venue that wants identifying information out of the
file itself:

    python -m src.export --anonymous

Outputs land in ``dist/``, which is gitignored. They are derived artifacts and
are rebuilt from source in one command, so committing them would be committing
a copy of something the repository can already produce.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PAPER = ROOT / "paper"
ASSETS = PAPER / "assets"
DIST = ROOT / "dist"
SOURCE = PAPER / "manuscript_built.md"
CITATION = ROOT / "CITATION.cff"

AFFILIATION = "Independent researcher"

# Bundled with typst, so the PDF renders identically wherever the build runs.
TYPST_FONT = "Libertinus Serif"

# Lines the built manuscript carries for the benefit of whoever edits the
# repository, which have no business in a submitted document. Matched on a
# distinctive fragment rather than the whole line, so rewording the banner does
# not silently stop stripping it.
INTERNAL_MARKERS = (
    "Every number in this document is generated by the analysis code",
    "Built from `paper/manuscript.md` by `src/report.py`",
)


class ExportError(RuntimeError):
    """Something the user has to fix, reported without a traceback."""


# --------------------------------------------------------------------------
# Identity, read from the citation record rather than retyped
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Identity:
    title: str
    author: str
    orcid: str
    keywords: list[str]
    version_doi: str

    @classmethod
    def load(cls) -> "Identity":
        cff = yaml.safe_load(CITATION.read_text(encoding="utf-8"))
        a = cff["authors"][0]
        return cls(
            title=" ".join(cff["title"].split()),
            author=f"{a['given-names']} {a['family-names']}",
            orcid=a.get("orcid", ""),
            keywords=list(cff.get("keywords", []))[:10],
            version_doi=cff.get("doi", ""),
        )


# --------------------------------------------------------------------------
# Source preparation
# --------------------------------------------------------------------------


def _strip_internal(text: str) -> str:
    """Drop the repository's own notes-to-self and the title block.

    The title and author line are removed here and reinstated as pandoc
    metadata, so the same document can be built with a full title page or
    with none at all.
    """
    lines = text.splitlines()
    kept = [
        ln for ln in lines
        if not any(m in ln for m in INTERNAL_MARKERS)
    ]
    out = "\n".join(kept)
    out = re.sub(r"^# .*?\n", "", out, count=1)
    out = re.sub(r"^\*\*Author:\*\*.*?\n", "", out, count=1, flags=re.M)
    # The first horizontal rule separated the stripped title block from the
    # abstract and now separates nothing.
    out = re.sub(r"\A[\s\-]*\n---\n", "", out)
    return out.lstrip("\n")


# Substitutions applied for --anonymous. Each replaces a specific identifying
# fact with a statement of what was removed, rather than deleting silently: a
# reviewer should be able to see that a data availability statement exists and
# was withheld, not conclude that the authors omitted one.
ANONYMOUS_RULES: list[tuple[str, str]] = [
    (
        r"\*\*ORCID\.\*\*[^\n]*\n\n",
        "",
    ),
    (
        r"\*\*Author contributions\.\*\*[^\n]*\n",
        "**Author contributions.** The sole author is responsible for all aspects "
        "of the work: conceptualisation, data curation, analysis, software, and "
        "writing. Author identity is withheld from this anonymised copy.\n",
    ),
    (
        r"\*\*Data availability\.\*\*[^\n]*\n",
        "**Data availability.** All code and data needed to reproduce every number "
        "and figure in this manuscript are archived in a public repository under a "
        "permanent DOI, and the analysis is fully reproducible from that archive. "
        "The DOI and repository URL identify the author and are withheld from this "
        "anonymised copy; they have been supplied to the editorial office.\n",
    ),
]

# Anything matching these must not survive into an anonymised build. Checked
# after the rules run, because a rule that stops matching -- the Declarations
# get reworded, say -- would otherwise fail open and ship the name.
IDENTIFYING = (
    r"Terry\s+Finberg",
    r"terryfinberg",
    r"orcid\.org/\d",
    r"0009-0006-1598-4200",
    r"10\.5281/zenodo",
    r"github\.com/\S+",
)


def _anonymise(text: str, identity: Identity) -> str:
    for pattern, replacement in ANONYMOUS_RULES:
        text = re.sub(pattern, replacement, text)
    text = text.replace(identity.author, "[author name withheld]")
    return text


def _assert_anonymous(text: str) -> None:
    hits = sorted({
        m.group(0)
        for pattern in IDENTIFYING
        for m in re.finditer(pattern, text, re.I)
    })
    if hits:
        raise ExportError(
            "anonymised build still contains identifying strings: "
            + ", ".join(repr(h) for h in hits)
            + "\nAdd a rule to ANONYMOUS_RULES in src/export.py."
        )


def prepare(identity: Identity, anonymous: bool) -> str:
    """The markdown that goes to pandoc, metadata block included."""
    body = _strip_internal(SOURCE.read_text(encoding="utf-8"))
    if anonymous:
        body = _anonymise(body, identity)
        _assert_anonymous(body)

    # Keywords go in the body, not the metadata block.
    #
    # Two reasons, one forced and one wanted. Pandoc 3.6.2's typst template
    # renders a keywords list as `keywords: (,,,,,,,,,)` -- it emits the
    # separators and not the values -- and typst then refuses the document.
    # That is a pandoc bug and it fires for every input form, inline list and
    # block sequence alike. Independently, Demographic Research asks for the
    # keywords to be *listed in the file*, which document properties nobody
    # opens do not satisfy. A visible line fixes both.
    #
    # The docx build still sets the document property, passed on the command
    # line where the writer handles it correctly. See build_docx().
    if identity.keywords:
        line = "**Keywords:** " + ", ".join(identity.keywords) + "\n"
        marker = "\n---\n\n## 1. Introduction"
        if marker in body:
            body = body.replace(marker, f"\n{line}{marker}", 1)
        else:
            raise ExportError(
                "could not place the keywords line: the abstract no longer "
                "ends with a rule before section 1. Fix the marker in "
                "src/export.py rather than dropping the keywords."
            )

    meta: dict = {
        "title": identity.title,
        "lang": "en-US",
    }
    if not anonymous:
        author: dict = {"name": identity.author, "affiliation": AFFILIATION}
        if identity.orcid:
            author["orcid"] = identity.orcid
        meta["author"] = [author]
        # Pandoc's default templates render a plain author list, so the
        # affiliation and ORCID are also emitted as a visible subtitle line.
        # Losing them to a template that ignores structured author fields is
        # the failure mode this avoids.
        byline = [identity.author, AFFILIATION]
        if identity.orcid:
            byline.append(f"ORCID: {identity.orcid}")
        meta["author"] = [" · ".join(byline)]
    else:
        meta["author"] = []

    front = yaml.safe_dump(meta, allow_unicode=True, sort_keys=False,
                           default_flow_style=False, width=100)
    return f"---\n{front}---\n\n{body}"


# --------------------------------------------------------------------------
# Pandoc
# --------------------------------------------------------------------------

# PDF engines in descending order of how well they suit a journal submission.
# The browser fallback is last and is genuinely a fallback: it is the only one
# whose output depends on a version of a program the repository cannot pin.
LATEX_ENGINES = ("tectonic", "xelatex", "lualatex", "pdflatex")
OTHER_ENGINES = ("typst", "weasyprint", "wkhtmltopdf")

BROWSERS = (
    Path("C:/Program Files/Google/Chrome/Application/chrome.exe"),
    Path("C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"),
)

# Writers that number figures and tables themselves. The Lua filter must not
# run for these or every caption reads "Figure 1: Figure 1: ...".
SELF_NUMBERING = {"latex", "typst", "context"}


def _require_pandoc() -> str:
    exe = shutil.which("pandoc")
    if not exe:
        raise ExportError(
            "pandoc is not installed, and every output here goes through it.\n"
            "  winget install --id JohnMacFarlane.Pandoc\n"
            "or see https://pandoc.org/installing.html"
        )
    return exe


def find_pdf_engine() -> tuple[str, str] | None:
    """(engine name, writer) for the best available engine, or None."""
    for name in LATEX_ENGINES:
        if shutil.which(name):
            return name, "latex"
    for name in OTHER_ENGINES:
        if shutil.which(name):
            return name, "typst" if name == "typst" else "html"
    return None


def find_browser() -> Path | None:
    for path in BROWSERS:
        if path.exists():
            return path
    return None


def _pandoc(md: str, out: Path, writer: str, extra: list[str]) -> None:
    cmd = [
        _require_pandoc(),
        "--from", "markdown+pipe_tables+implicit_figures+yaml_metadata_block",
        "--standalone",
        "--resource-path", str(ROOT),
        "--output", str(out),
    ]
    if writer not in SELF_NUMBERING:
        cmd += ["--lua-filter", str(ASSETS / "number-captions.lua")]
    cmd += extra
    result = subprocess.run(cmd, input=md, text=True, encoding="utf-8",
                            capture_output=True, cwd=ROOT)
    if result.returncode != 0:
        raise ExportError(
            f"pandoc failed writing {out.name}:\n{result.stderr.strip()}"
        )
    if result.stderr.strip():
        for line in result.stderr.strip().splitlines():
            print(f"    pandoc: {line}", file=sys.stderr)


def build_docx(md: str, out: Path, keywords: list[str] | None = None) -> Path:
    extra = ["--to", "docx", "--toc-depth", "3"]
    if keywords:
        # Word's Keywords document property. Passed here rather than in the
        # YAML block because the same key breaks the typst writer; see
        # prepare().
        extra += ["--metadata", "keywords=" + ", ".join(keywords)]
    _pandoc(md, out, "docx", extra)
    return out


def build_pdf(md: str, out: Path, allow_browser: bool = False) -> tuple[Path, str]:
    """Returns (path, description of the engine used).

    The browser fallback is opt-in. It was not, and the reason it is now is
    worth keeping: a run that quietly degrades to headless Chrome prints one
    line saying so, and one line is easy to scroll past. A PDF built that way
    is indistinguishable from a good one until somebody reads its metadata,
    which is a poor place to discover it after a preprint is posted.

    Failing instead means the person who wanted a submission PDF is told to
    install an engine, and the person who genuinely wants a rough preview
    passes --allow-browser-fallback and knows what they are getting.
    """
    engine = find_pdf_engine()
    if engine:
        name, writer = engine
        extra = ["--pdf-engine", name]
        if writer == "latex":
            extra += [
                "--variable", "geometry:margin=1in",
                "--variable", "fontsize=11pt",
                "--variable", "linkcolor=blue",
            ]
        elif writer == "typst":
            # A font must be named. Pandoc's typst template defaults to
            # `font: ()` and typst 0.15 rejects an empty fallback list with
            # "font fallback list must not be empty", so the document fails to
            # compile at all rather than falling back to a default.
            #
            # Libertinus Serif ships with typst itself, so this renders the
            # same on any machine that can run the build -- which a
            # system-installed face like Georgia would not.
            extra += [
                "--variable", f"mainfont={TYPST_FONT}",
                "--variable", "fontsize=11pt",
            ]
        _pandoc(md, out, writer, extra)
        return out, name

    install_hint = (
        "  winget install --id Typst.Typst          (small, fast, recommended)\n"
        "  winget install --id MiKTeX.MiKTeX        (full LaTeX)\n"
        "then re-run. DOCX needs neither and builds already.\n"
        "\n"
        "If a rough preview is all you want, --allow-browser-fallback renders it\n"
        "through headless Chrome. Do not submit that output: it depends on a\n"
        "browser version this repository cannot pin."
    )
    if not allow_browser:
        raise ExportError(
            "No PDF engine found, and the browser fallback is opt-in.\n"
            f"{install_hint}"
        )

    browser = find_browser()
    if not browser:
        raise ExportError(
            "No PDF engine, and no browser to fall back on either. Install one:\n"
            f"{install_hint}"
        )

    html = out.with_suffix(".html")
    _pandoc(md, html, "html", [
        "--to", "html5",
        "--embed-resources",
        "--css", str(ASSETS / "export.css"),
        "--metadata", "document-css=false",
    ])
    subprocess.run(
        [str(browser), "--headless", "--disable-gpu", "--no-pdf-header-footer",
         "--run-all-compositor-stages-before-draw",
         f"--print-to-pdf={out}", html.resolve().as_uri()],
        check=True, capture_output=True, timeout=180,
    )
    if not out.exists():
        raise ExportError(f"{browser.name} produced no PDF at {out}")
    return out, f"{browser.stem} headless (fallback)"


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def _git(*args: str) -> str:
    try:
        r = subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                           text=True, timeout=15)
        return r.stdout.strip() if r.returncode == 0 else "?"
    except Exception:
        return "?"


def write_manifest(engine: str | None, files: list[Path]) -> Path:
    """Record what produced these artifacts, next to the artifacts.

    The engine is printed on every run, but a printed line lives only as long
    as the terminal does. Once it is gone the only way to answer "which engine
    made this PDF" is to read the file's own metadata, which is a question
    that came up for real and should not need forensics twice.

    The commit and the dirty flag matter as much as the engine: a submission
    PDF built from a working tree with uncommitted changes does not correspond
    to any archived release, and that is exactly the divergence between a
    posted preprint and its deposit that the release ordering exists to stop.
    """
    described = _git("describe", "--tags", "--always", "--dirty")
    lines = [
        "Build record for the artifacts in this directory.",
        "Written by src/export.py. Not committed; dist/ is gitignored.",
        "",
        f"built            {datetime.now().astimezone().isoformat(timespec='seconds')}",
        f"git describe     {described}",
        f"commit           {_git('rev-parse', 'HEAD')}",
        f"working tree     {'DIRTY -- does not match any commit' if described.endswith('-dirty') else 'clean'}",
        f"pdf engine       {engine or '(no PDF built)'}",
        f"pandoc           {_pandoc_version()}",
        "",
        "files:",
        *(f"  {p.name}" for p in files),
    ]
    path = DIST / "BUILD.txt"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _pandoc_version() -> str:
    try:
        r = subprocess.run([_require_pandoc(), "--version"],
                           capture_output=True, text=True, timeout=15)
        return r.stdout.splitlines()[0].strip() if r.returncode == 0 else "?"
    except Exception:
        return "?"


def run(pdf: bool, docx: bool, anonymous: bool, allow_browser: bool = False) -> list[Path]:
    if not SOURCE.exists():
        raise ExportError(
            f"{SOURCE.relative_to(ROOT)} does not exist. Run "
            "`python -m src.report` first; the export builds from the "
            "generated manuscript, never from the template."
        )
    identity = Identity.load()
    md = prepare(identity, anonymous)
    DIST.mkdir(exist_ok=True)

    stem = "manuscript-anonymous" if anonymous else "manuscript"
    written: list[Path] = []

    if docx:
        out = build_docx(md, DIST / f"{stem}.docx", identity.keywords)
        print(f"  DOCX  {out.relative_to(ROOT)}")
        written.append(out)
    engine = None
    if pdf:
        out, engine = build_pdf(md, DIST / f"{stem}.pdf", allow_browser)
        print(f"  PDF   {out.relative_to(ROOT)}  [{engine}]")
        if "fallback" in engine:
            print("  ^^^^  NOT a submission artifact. See --allow-browser-fallback.")
        written.append(out)
    run.last_engine = engine  # type: ignore[attr-defined]
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="python -m src.export",
        description="Build submission artifacts from paper/manuscript_built.md.",
    )
    ap.add_argument("--pdf", action="store_true", help="build the PDF only")
    ap.add_argument("--docx", action="store_true", help="build the DOCX only")
    ap.add_argument(
        "--anonymous", action="store_true",
        help="strip author name, ORCID, affiliation, and neutralise the "
             "repository and DOI references",
    )
    ap.add_argument(
        "--both", action="store_true",
        help="build identified and anonymised variants in one run",
    )
    ap.add_argument(
        "--allow-browser-fallback", action="store_true",
        help="permit rendering the PDF through headless Chrome when no real "
             "engine is installed. Produces a preview, not a submission "
             "artifact: the output depends on a browser version this "
             "repository cannot pin. Without this flag, a missing engine is "
             "an error.",
    )
    args = ap.parse_args(argv)

    # Neither flag means both formats, which is what a bare invocation should
    # do. --pdf and --docx together mean the same thing.
    pdf = args.pdf or not (args.pdf or args.docx)
    docx = args.docx or not (args.pdf or args.docx)

    try:
        variants = [False, True] if args.both else [args.anonymous]
        produced: list[Path] = []
        for anonymous in variants:
            print("anonymised:" if anonymous else "identified:")
            produced += run(pdf, docx, anonymous, args.allow_browser_fallback)
        manifest = write_manifest(
            getattr(run, "last_engine", None), produced
        )
        print(f"\n  {manifest.relative_to(ROOT)}  records the engine, commit "
              "and tree state")
    except ExportError as exc:
        print(f"\nerror: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
